### ISSUE TITLE
Models with free functions in other modules

### ISSUE THREAD

**Issue by jmh530** [atilaneves/concepts#6]
On the Learn forum, there was a recent [question](https://forum.dlang.org/post/pb2sec$1isf$1@digitalmars.com) about using std.range's isInputRange with free functions.

I was able to get a version working with template mixins (see thread), but it would be nice if there were a more general solution. Based on the forum discussion, I'm not sure it can be done with a compiler enhancement.

**Comment by atilaneves** [comment]
I'm not sure it can be done without changing the language either.

**Comment by jmh530** [comment]
If that's case I can close this.
